{"timestamp":"2025-10-07T01:45:52.774920Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-07T01:45:52.775220Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/airflow.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-07T01:45:53.201300Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/airflow.py","lineno":9,"logger":"py.warnings"}
{"timestamp":"2025-10-07T01:45:53.210445Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.210836Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.211062Z","level":"info","event":"Current task name:load_data","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.211124Z","level":"info","event":"Dag name:wine_classification","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.212316Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"KeyError","exc_value":"\"['target'] not found in axis\"","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/airflow.py","lineno":21,"name":"load_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py","lineno":5344,"name":"drop"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":4711,"name":"drop"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":4753,"name":"_drop_axis"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py","lineno":7000,"name":"drop"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-07T01:45:53.212984Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.214426Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.216402Z","level":"info","event":"Task:<Task(PythonOperator): load_data>","logger":"task.stdout"}
{"timestamp":"2025-10-07T01:45:53.216520Z","level":"info","event":"Failure caused by \"['target'] not found in axis\"","logger":"task.stdout"}
